// Generated by CoffeeScript 1.3.3
(function() {

  exports.makeHandler = function() {
    var handler;
    return handler = function(stream) {
      return stream.endWithMime('', 'image/vnd.microsoft.icon');
    };
  };

}).call(this);
