// Generated by CoffeeScript 1.3.3
(function() {
  var fs, handlebars;

  handlebars = require('handlebars');

  fs = require('fs');

  exports.makeHandler = function(filename, context) {
    var handler;
    handler = function(stream) {
      var _this = this;
      return fs.readFile(filename, function(err, data) {
        var template;
        if (err) {
          return stream.log.error(err);
        }
        template = handlebars.compile(data.toString());
        return stream.end(template(context));
      });
    };
    return handler;
  };

}).call(this);
