// Generated by CoffeeScript 1.3.3
(function() {
  var fs, less;

  less = require('less');

  fs = require('fs');

  exports.makeHandler = function(dir, config) {
    var handler, parser, _ref, _ref1, _ref2;
    if (config == null) {
      config = {};
    }
    config.filename = dir;
    if ((_ref = config.compress) == null) {
      config.compress = false;
    }
    if ((_ref1 = config.paths) == null) {
      config.paths = [];
    }
    if ((_ref2 = config.optimization) == null) {
      config.optimization = 1;
    }
    parser = new less.Parser(config);
    handler = function(stream) {
      var _this = this;
      return fs.readFile(config.filename, function(err, data) {
        if (err) {
          return stream.log.error(err);
        }
        return parser.parse(data.toString(), function(err, tree) {
          if (err) {
            return stream.log.error(err);
          }
          stream.setMime('text/css');
          return stream.end(tree.toCSS({
            compress: config.compress
          }));
        });
      });
    };
    return handler;
  };

}).call(this);
