// Generated by CoffeeScript 1.3.3
(function() {
  var defaultMimeTypes, fs, matchMimeType, p, routePath;

  fs = require('fs');

  p = require('path');

  routePath = function(path, config) {
    var filename, handler, stat, _fn, _i, _len, _ref, _ref1;
    if (config == null) {
      config = {};
    }
    if ((_ref = config.mimeTypes) == null) {
      config.mimeTypes = {};
    }
    stat = fs.statSync(path);
    handler = void 0;
    if (stat.isDirectory()) {
      handler = {};
      _ref1 = fs.readdirSync(path);
      _fn = function(filename) {
        if (fs.existsSync(p.join(path, filename))) {
          return handler[filename] = routePath(p.join(path, filename));
        }
      };
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        filename = _ref1[_i];
        _fn(filename);
      }
    } else if (stat.isFile() && fs.existsSync(path)) {
      handler = function(stream) {
        var fileStream, match, mimeTypes, type, _ref2;
        mimeTypes = {};
        for (match in defaultMimeTypes) {
          type = defaultMimeTypes[match];
          mimeTypes[match] = type;
        }
        _ref2 = config.mimeTypes;
        for (match in _ref2) {
          type = _ref2[match];
          mimeTypes[match] = type;
        }
        type = matchMimeType(path, mimeTypes, 'text/plain');
        stream.setMime(type);
        fileStream = fs.createReadStream(path);
        fileStream.on('error', function(e) {
          return stream.log.error("" + err.message);
        });
        return fileStream.pipe(stream);
      };
    } else {
      handler = function(stream) {
        return stream.log.warn("IGNORING " + path + ": neither file nor directory");
      };
    }
    return handler;
  };

  matchMimeType = function(path, types, defaultType) {
    var e, t, ts;
    ts = (function() {
      var _results;
      _results = [];
      for (e in types) {
        t = types[e];
        if ((new RegExp("" + e + "$")).test(path)) {
          _results.push([e.length, t]);
        }
      }
      return _results;
    })();
    ts.sort();
    if (ts.length > 0) {
      return ts.pop()[1];
    } else {
      return defaultType;
    }
  };

  defaultMimeTypes = {
    '.txt': 'text/plain',
    '.htm': 'text/html',
    '.html': 'text/html',
    '.css': 'text/css',
    '.coffee': 'text/coffeescript',
    '.js': 'application/javascript',
    '.json': 'application/json',
    '.xhtml': 'application/xhtml+xml',
    '.xml': 'application/xml',
    '.gif': 'image/gif',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.svg': 'image/svg+xml',
    '.ico': 'image/vnd.microsoft.icon'
  };

  exports.makeHandler = routePath;

}).call(this);
